language: php

php:
  - 7.4
  - 8.1

before_script:
  - if [[ $TRAVIS_SECURE_ENV_VARS = "true" ]]; then composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH; fi
  - echo 'xdebug.mode = coverage' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - docker run -p 10000:10000 -p 10001:10001 -d mcr.microsoft.com/azure-storage/azurite
  - docker run -p 9324:9324 -d softwaremill/elasticmq
  - docker run -p 8681:8681 -d messagebird/gcloud-pubsub-emulator:latest
  - docker run -p 11300:11300 -d schickling/beanstalkd
  - docker run -p 6379:6379 -d redis
  - composer install --no-interaction

script: bin/kahlan --coverage=3 --clover=clover.xml

after_success:
  - "if [ $(phpenv version-name) = '7.4' ]; then wget https://scrutinizer-ci.com/ocular.phar; fi"
  - "if [ $(phpenv version-name) = '7.4' ]; then php ocular.phar code-coverage:upload --format=php-clover 'clover.xml'; fi"

env:
  global:
    secure: HSEyzHxfy+FAs2HEVr5IdANrLpWzrw24pD0Q0u7D6J4+4ZW62aBfdz2oZUte0F6JU0dvF95l4kN8CpWxEyDg8hWYOkAc3F9f7fq1jKeU0gumg8MyCrvvN7xvhtLVvHw93rEguG+3zFeufo4ADrjBK88sFiieTiPrnsxTXH0yIMWHBeWFhTzLvihssoPWjV2RI/dS54Jt27QG8qyZiMFbj7rodEEje0LmqcmL6pKXoRpZwfKo32U5IX4N7Z5DSQ1nt1lkRUuK/FOu50X5Xjlb76OiLIaANCITkZUBzh8Sj2TNaxrTNxgFaoCEFHsD8sir9/OGaniHlV0jRKzdcXQu0qzKkyfwMj1u+0H8K4/H5HpXq/kj93UQ8aW8kVM+ny00BeG/WoLLkcnZ6Zjf12xIxWZ+gyQoeTWyiV7wZhccOz/Y5JC6G3JX8N3m0v9wSZ7niKeMajfYfTuYbQcSvefQ1NJN72Ou32yvEwYXcVGmLthrP+2tCYTXj9qVPTRlkrQOgHedXx4M/eCLH3/Bi4fgERlpPNCUeYOQ5lRbwWDDp9gsV2oCH/AJiRAEt673AroTEXBgcv6zrHLRlyDqEZ4aL2LWlAVtO9xj/3v1B4R5Q97+hlc3zoF2gUYDizCvmazA7reRmH9EqGaBlNw8jsxcthW4lIaS44WoNXBkbGqztGE=
